#lang sicp

(define (make-account balance password)
  (let ((try-count 0))
    (define call-the-cops
      (lambda ()
        "Cops are called"))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Недостаточно денег на счете"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch check-pass m)
      (cond
        ((not (eq? check-pass password))
         (lambda (val)
           (set! try-count (+ try-count 1))
           (if (> try-count 7)
               (call-the-cops)
               "Wrong password")))
        ((eq? m 'withdraw) withdraw)
        ((eq? m 'deposit) deposit)
        (else (error "Неизвестный вызов -- MAKE-ACCOUNT" m))))
    dispatch))